name: catatan_projek
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.1
  hive: 2.0.5
  hive_flutter: 1.1.0
  intl: 0.17.0
  uuid: 3.0.5

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test:
    sdk: flutter
  build_runner: 2.1.7

flutter:
  uses-material-design: true
